# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-29 21:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pastie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scrape_url', models.CharField(max_length=255)),
                ('full_url', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('key', models.CharField(max_length=10)),
                ('size', models.IntegerField()),
                ('expire', models.DateField()),
                ('title', models.CharField(max_length=255)),
                ('syntax', models.CharField(max_length=50)),
                ('user', models.CharField(max_length=255)),
            ],
        ),
    ]
