# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-04 10:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20171129_2221'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pastie',
            options={'ordering': ['date']},
        ),
        migrations.AlterField(
            model_name='pastie',
            name='key',
            field=models.CharField(db_index=True, max_length=10),
        ),
    ]
