# Generated by Django 2.1.3 on 2018-11-29 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20171204_1011'),
    ]

    operations = [
        migrations.AddField(
            model_name='pastie',
            name='content',
            field=models.TextField(null=True),
        ),
    ]
